### ISSUE TITLE
egs_view keeps crashing

### ISSUE THREAD

**Issue by jcampbell555** [nrc-cnrc/EGSnrc#770]
I'm making my way through the Getting Started manual and was successful the first time around up to "4.5 Change the type of incident particles". I took a break for a few days and came back to try to reproduce my work but I can't seem to run egs_view. I've tried to use the command prompt to open it using the egs_view command as well as opening it directly from the file location and my desktop shortcut. It will open for a few seconds and then close. Any help would be appreciated :)

Update: I deleted all my egsnrc files and reinstalled them. This worked but then after running the first simulation, the egs_view application refuses to open. I get a "view_debug" file in multiple locations on my computer claiming that the file im trying to use doesn't exist anymore.

**Comment by ftessier** [comment]
Are you working on Windows or Linux? I presume it was working before, up to this point, correct?

**Comment by jcampbell555** [comment]
I'm working on Windows and yes it was working before

**Comment by rtownson** [comment]
When you open it from the desktop shortcut, do you get the file selection dialog before it crashes? If it crashes after selecting the input file, try opening a different input file instead. A mistake in the input file can cause a crash like this (feel free to post it here, if you determine that to be the case). If egs_view crashes before selecting an input file, then I would try running the installer GUI again and making sure you check the box to create desktop shortcuts. If the desktop shortcut still doesn't work, then post your installation log here, found in HEN_HOUSE/log.

**Comment by jcampbell555** [comment]
@rtownson The file selection dialogue pops up and after uninstalling and reinstalling again I can now open those  input files. However, I still can't call the program from the command prompt.

**Comment by rtownson** [comment]
Does it work on the command line if you 'cd' into `HEN_HOUSE\egs++\dso\win-static` first?

**Comment by ftessier** [comment]
Indeed, most likely a `PATH` issue.

**Comment by ftessier** [comment]
Is this resolved? Another user is reporting `egs_view` not working on Windows:

> I successfully was able to create the executable named `myapp` and the input file named `slab.egsinp` (as instructed in the guide).  I then was able to run successfully the executable `myapp` with the input file `slab.egs.inp` since I could see the results of the simulation being displayed on the computer screen as soon as I ran it. So up to here all looked good. The problem I am having is when I try to view the output file created called `slab.ptracks`. When I try to open it using `egs_view` (as instructed in the guide) a window opens for about 2 seconds and then disappears. So the problem I am having seems to be using `egs_view`.

**Comment by ftessier** [comment]
Turns out the issue reported in the previous comment was trying to open the `.ptracks` file directly, instead of the `.egsinp` file initially.

@rtownson, may we add a filename filter in the initial egs_view file select box to only show `*.egsinp` files?

**Comment by mainegra** [comment]
The user having that problem was using the command line as well: egs_view slab.egsinp slab.ptracks
But not on the application folder! ;-)
**Eureka:** Problem solved!

**Comment by ftessier** [comment]
@mainegra you mean it was resolved for @jcampbell555 as well, upon running from the appropriate folder?

**Comment by mainegra** [comment]
Nope. I interacted with the other user. I think.

**Comment by jcampbell555** [comment]
Yeah, I'm still having an issue from the command line. I'm not entirely certain why it won't run from there. I've been running directly through the egs_view app on the desktop.

**Comment by ftessier** [comment]
Thank you for the update!
